version: '3.8'

services:
  frontend-app:
    build:
      context: ..  # Path to root of the repo
      dockerfile: docker/Dockerfile
      args:
        NODE_VERSION: 20
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
        NEXT_PUBLIC_GITHUB_CLIENT_ID: ${NEXT_PUBLIC_GITHUB_CLIENT_ID}
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
        NEXT_PUBLIC_DOCKER_BACKEND_URL: ${NEXT_PUBLIC_DOCKER_BACKEND_URL}
        ENV: ${ENV}
        NEXT_PUBLIC_ENV: ${NEXT_PUBLIC_ENV}
    container_name: scholar-ai-frontend
    ports:
      - "3000:3000"
    env_file:
      - ../.env  # ✅ Explicitly include .env file
    environment:
      # Runtime environment variables
      NEXT_TELEMETRY_DISABLED: "1"
      ENV: ${ENV}
      NEXT_PUBLIC_ENV: ${NEXT_PUBLIC_ENV}
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
      NEXT_PUBLIC_DOCKER_BACKEND_URL: ${NEXT_PUBLIC_DOCKER_BACKEND_URL}
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
      NEXT_PUBLIC_GITHUB_CLIENT_ID: ${NEXT_PUBLIC_GITHUB_CLIENT_ID}
    restart: unless-stopped
    networks:
      - scholar_network_alias

networks:
  scholar_network_alias:
    external: true
    name: docker_scholar-network
