name: Frontend CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  AZURE_CONTAINER_REGISTRY: scholarai
  RESOURCE_GROUP: scholarai-rg
  CONTAINER_NAME: scholarai-frontend
  IMAGE_NAME: scholarai-frontend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests (if available)
      run: npm test -- --passWithNoTests || echo "No tests found, skipping..."
    
    - name: Build application
      run: npm run build

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Login to Azure Container Registry
      run: |
        az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY }}
    
    - name: Build and push Docker image
      run: |
        docker build \
          --build-arg NEXT_PUBLIC_API_BASE_URL=http://scholarai-buet-api.eastus.azurecontainer.io:8080 \
          --build-arg NEXT_PUBLIC_DOCKER_BACKEND_URL=http://scholarai-buet-fastapi.eastus.azurecontainer.io:8000 \
          --build-arg NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }} \
          --build-arg NEXT_PUBLIC_GITHUB_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GITHUB_CLIENT_ID }} \
          --build-arg ENV=prod \
          --build-arg NEXT_PUBLIC_ENV=prod \
          -t ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          -t ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest \
          -f docker/Dockerfile .
        
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
    
    - name: Deploy to Azure Container Instances
      run: |
        # Clean up any existing Frontend containers (including old ones)
        echo "🧹 Cleaning up ALL existing Frontend containers..."
        for pattern in "frontend" "buet-frontend" "scholarai-frontend"; do
          echo "Looking for Frontend containers with pattern: $pattern"
          for container in $(az container list --resource-group ${{ env.RESOURCE_GROUP }} --query "[?contains(name, '$pattern')].name" --output tsv); do
            if [ ! -z "$container" ]; then
              echo "Deleting container: $container"
              az container delete --resource-group ${{ env.RESOURCE_GROUP }} --name $container --yes
            fi
          done
        done
        
        # Wait a moment for cleanup
        sleep 15
        
        # Create new container
        az container create \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --name scholarai-buet-frontend \
          --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          --registry-login-server ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io \
          --registry-username ${{ secrets.ACR_USERNAME }} \
          --registry-password ${{ secrets.ACR_PASSWORD }} \
          --dns-name-label scholarai-buet-app \
          --os-type Linux \
          --ports 3000 \
          --cpu 0.25 \
          --memory 0.5 \
          --environment-variables \
            NODE_ENV=production \
            NEXT_TELEMETRY_DISABLED=1 \
            ENV=prod \
            NEXT_PUBLIC_ENV=prod \
            NEXT_PUBLIC_API_BASE_URL=http://scholarai-buet-api.eastus.azurecontainer.io:8080 \
            NEXT_PUBLIC_DOCKER_BACKEND_URL=http://scholarai-buet-fastapi.eastus.azurecontainer.io:8000 \
            NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }} \
            NEXT_PUBLIC_GITHUB_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GITHUB_CLIENT_ID }} \
          --restart-policy Always
        
        echo "Frontend deployed successfully!"
        echo "🌐 Frontend: http://scholarai-buet-app.eastus.azurecontainer.io:3000" 